# Generated by Django 3.0.4 on 2020-03-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Article')),
            ],
        ),
    ]
