# Generated by Django 3.0.4 on 2020-03-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20200315_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
    ]
