# Generated by Django 3.0.4 on 2020-03-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
