# Generated by Django 3.0.4 on 2020-03-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
